name: Build and Upload Python Package

on:
  push:

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install nox
        run: python -m pip install nox
      - name: Build sdist
        run: nox -s build_sdist

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/*.tar.gz
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/*.whl
